### ISSUE TITLE
Send a request with Authorization header

### ISSUE THREAD

**Issue by LindomarReitz** [SEEK-Jobs/pact-net#104]
Hello,

I'm having the problem to send a request with an Authorization header, because the PactVerifier.ServiceProvider only accepts the URI string.

In the previous version was possible to send a HttpClient, but it was removed in this commit: https://github.com/SEEK-Jobs/pact-net/commit/4d9b0b5f66a168f25cedb95590881f14b67e4da9#diff-cd5b8831bba1394e9a1d6c47643a8be5L83

How can I send a request with an Authorization header in this case?

**Comment by neilcampbell** [comment]
Hi @LindomarReitz 
Thanks for getting in touch.

Yeah unfortunately we had to remove the HttpClient mode, as we wanted to move to using the shared ruby core.

My advice is to include the authorization header in the consumer side pact file instead.
Basically you would generate a deterministic dummy token when writing the consumer test, and when starting the provider for verification inject some kind of middleware which recognizes that specific token and validates it as a genuine token. Obviously this middleware would only be injected by the tests and never in a production scenario. The samples in the repo actually have an example of this. See https://github.com/SEEK-Jobs/pact-net/blob/master/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs#L107, https://github.com/SEEK-Jobs/pact-net/blob/master/Samples/EventApi/Provider.Api.Web.Tests/AuthorizationTokenReplacementMiddleware.cs and https://github.com/SEEK-Jobs/pact-net/blob/master/Samples/EventApi/Provider.Api.Web.Tests/TestStartup.cs#L13

**Comment by bethesque** [comment]
I've added a `--custom-provider-header` option in the standalone 1.3.0. See documentation here: https://github.com/pact-foundation/pact-provider-verifier#setting-a-custom-authentication-header

**Comment by neilcampbell** [comment]
@LindomarReitz This has now been added to the latest nuget package (2.0.13-beta). This is exposed via PactVerifierConfig.CustomHeader
