### ISSUE TITLE
Ensure PACT_DESCRIPTION and PACT_PROVIDER_STATE env vars can be passed down to pact verify to allow selected interactions to be run

### ISSUE THREAD

**Issue by bethesque** [SEEK-Jobs/pact-net#105]
I've removed the ruby specific output from the pact verify command (yay!)

What I would like to add is words to the effect of "to run just one interaction, please rerun the pact verify command with PACT_DESCRIPTION="..." and PACT_PROVIDER_STATE="..." environment variables set.

Can you please update to the ruby standalone version 1.4.0 and verify that the above environment variables are passed through? You should see the text `Filtering interactions by...`

**Comment by neilcampbell** [comment]
@bethesque Awesome stuff!

When starting the process, we setup the environment variables for the process, so we could actually set PACT_DESCRIPTION and PACT_PROVIDER_STATE for the user if they pass it to the verifier.Verify() method. I think this is easier for the user, however the output messages becomes a bit confusing.

**Comment by bethesque** [comment]
Filtering is something that you do temporarily, rather than something you want to put in the code and check in, so it make sense (to me!) be able to configure it from the environment rather than the code. However, I guess there are many people in windows environments who don't use the command line, or who aren't used to setting environment variables. Happy to take suggestions as to what the most useful output is.

**Comment by neilcampbell** [comment]
Yeah totally. I think I agree with that. I found when we had it configurable via code, people would misinterpret and misuse it.

**Comment by neilcampbell** [comment]
This has been tested and works correctly.

**Comment by bethesque** [comment]
There is the output at the bottom of the specs when they fail that gives you information on how to run the individual interactions. For the ruby specs it looks like this:

```
bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="a test request" PACT_PROVIDER_STATE="the weather is cloudy" # A test request given the weather is cloudy
bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="another test request" PACT_PROVIDER_STATE="" # Another test request
bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="another test request" PACT_PROVIDER_STATE="a missing provider state" # Another test request given a missing provider state
```

So, to just run the first failing spec, the user would copy that first line and run it

```
bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="a test request" PACT_PROVIDER_STATE="the weather is cloudy"
```

The text for the "re-run command" is actually configurable, so each wrapper language (.net, python, js etc) can configure its own "re-run command" template. The one for ruby is:

```
PACT_INTERACTION_RERUN_COMMAND="bundle exec rake pact:verify:at[<PACT_URI>] PACT_DESCRIPTION=\"<PACT_DESCRIPTION>\" PACT_PROVIDER_STATE=\"<PACT_PROVIDER_STATE>\""
```

It's a few levels of Inception deep, but the `<PACT_URI>`, `<PACT_DESCRIPTION>` and `<PACT_PROVIDER_STATE>` will be replaced with their live values when generating and outputting the re-run commands when the tests fail.

I think that perhaps I didn't bring it up for the .net implementation because I wasn't sure if anyone ever ran anything from the command line. We can make the message print out whatever helpful text is required to instruct users on how to set the relevant environment variables and re-run the verification command.

**Comment by neilcampbell** [comment]
@bethesque Yeah that's a little tricky. Most of common test runners are GUI based, and there is not one specific test framework that is used by everyone. I may need to add those two params back as arguments to the Verify method, and then set the text to show what the Verify method needs to look like. Thoughts?

**Comment by bethesque** [comment]
Sounds like that's the best way to make it work on windows. The text should include something about not checking the filters in accidentally!
