### ISSUE TITLE
Consumer need to call the MockProviderService before pact file will be generated.

### ISSUE THREAD

**Issue by jdstuart** [SEEK-Jobs/pact-net#107]
The PackBuilder does not generate a pact file if there are no consumer client calls made against the MockProviderService. As soon as requests are made, the pact files will be written.

Don't know if this is intentional or not.

**Comment by neilcampbell** [comment]
@jdstuart That's interesting, it was something that I was not aware of. I'm assuming you are referring to the latest beta version of the package? Also to confirm you are calling pactBuilder.Build()?

**Comment by jdstuart** [comment]
Correct. I tried with the latest beta, 2.0.7, I believe. And yes. I'm calling pactBuilder.Build().

You can basically reproduce the issue by commenting out line 51-57 in the [EventsApiConsumerTests.cs](https://github.com/SEEK-Jobs/pact-net/blob/master/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs)

**Comment by neilcampbell** [comment]
@jdstuart Thanks! Is there a specific reason you are wanting the Pact file, but are not making any consumer calls?

@bethesque Is this the behaviour expected from the Ruby core?

**Comment by jdstuart** [comment]
Yes, actually there is. I was given an API spec with no actual JSON examples in it. I want to create the pact files so I can share it with the producer (API server) and ask them to validate my assumptions before I go ahead and develop the complete consumer. If possible I'd like to produce the pacts using the .NET library so I can get some work done, but not do too much that I may have to change in the future.
It's also a timing thing. If I don't have to write all the consumer code up front, I can share the pacts sooner and ask them to validate it. After I received validation I can start adding the consumer code and modify the tests for that the consumer gets validated against the pacts.
Make sense?

**Comment by bethesque** [comment]
The mock service will only write verified interactions to the pact file, where "verified" means that the interaction was both mocked and replayed successfully by the test code. This is to stop the scenario where you write interactions to a pact file that your code doesn't actually execute.

**Comment by bethesque** [comment]
@jdstuart I'm sorry, the way the mock service currently behaves doesn't support your workflow. You could just execute the calls "manually" (ie. just using a basic HTTP client) in your tests to force the interactions to be written to the pact file.
