### ISSUE TITLE
ProviderServicePactFile

### ISSUE THREAD

**Issue by b3hdad** [SEEK-Jobs/pact-net#111]
Hello,
I was wondering what happened to the ProviderServicePactFile class. I upgraded the pact.net in the stub library, to the latest version and I am getting error that this class doesn't exist. 

Do you have any suggestions?

Thanks.
Behdad.

**Comment by neilcampbell** [comment]
Hey @b3hdad 
Now that we use the ruby host as the engine, it takes care of writing the Pact file for us, so we don't need that model anymore.

What are you using ProviderServicePactFile for?

**Comment by b3hdad** [comment]
Hi @neilcampbell,

If you go to the bottom of the page for Pact.Net, you will see I have referenced two tools. One is the Pact.Net Stubbing library and one is the Simulator. Both of which can be used to isolate services based on what is in the pact file. So to stub a service, during pact automation, one can add the stub library to the project, and provide the pact file and the library will act as that as that service.

So I was using this class to read the pact file to construct a response and send back to the dependent service. 

There are quite a few downloads on the library. Not sure what we can do?

**Comment by neilcampbell** [comment]
Ah yep, thought it may be for those.
You can still do it, you will just need to create you own copy of that type (ProviderServicePactFile) and read the pact file from disc, then deserialise into a ProviderServicePactFile or call whatever you want to call it.

**Comment by b3hdad** [comment]
If I do it this way wouldn't the schema go out of sync with the class over time?

**Comment by neilcampbell** [comment]
Yeah it may do when the pact specification changes, however that is very infrequent.

**Comment by b3hdad** [comment]
Ok sure. Thanks @neilcampbell , I will find the class in git history and move it the tools.

**Comment by neilcampbell** [comment]
https://github.com/SEEK-Jobs/pact-net/blob/1.3.2/PactNet/Mocks/MockHttpService/Models/ProviderServicePactFile.cs
