### ISSUE TITLE
MinType Matcher Generates Unsupported Matching Rule

### ISSUE THREAD

**Issue by adamrodger** [SEEK-Jobs/pact-net#112]
I have a matching rule in my consumer like this:
```csharp
this.mockProviderService
    .UponReceiving("A GET request to retrieve all values")
    .With(new ProviderServiceRequest
    {
        Method = HttpVerb.Get,
        Path = "/api/values",
        Headers = new Dictionary<string, object> { { "Accept", "application/json" } }
    })
    .WillRespondWith(new ProviderServiceResponse
    {
        Status = 200,
        Headers = new Dictionary<string, object> { { "Content-Type", "application/json; charset=utf-8" } },
        Body = new { values = Match.MinType("example", 1) }
    });

await this.client.GetAsync("/api/values");

this.mockProviderService.VerifyInteractions();
```

where "values" is just a simple array of strings. This generates a Pact containing:
```json
"matchingRules": {
  "$.body.values": {
    "min": 1
  },
  "$.body.values[*].*": {
    "match": "type"
  }
}
````

However, when I try to verify that Pact in my provider, I get:
```
WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['values']
```

I'm not sure if it's PactNet generating an invalid matching rule or the Ruby standalone runner not interpreting them properly, but I'm using PactNet.Windows v2.0.17 so I'll raise it here in the first instance.

I've created a demo repo to show the issue here: https://github.com/adamrodger/pact-list-test

**Comment by adamrodger** [comment]
I've just done some experimenting and even though you get the message saying the rule is unsupported, it does seem to actually still be applied.

If I set it to `Match.MinType("example", 3)` but the response only returns a 2-element array, the verification fails because the array is too short. Even though it looks like the rule was being ignored, perhaps the error message isn't actually true.

**Comment by neilcampbell** [comment]
@bethesque Any ideas on this? I noticed this https://github.com/pact-foundation/pact-support/issues/35. 2.0.17 uses the latest ruby standalone.

**Comment by bethesque** [comment]
It's one of those things that's been floating around for ages and it's never gotten to the top of my priority list as it doesn't seem to be affecting behaviour. Raise an issue in pact-support and I'll investigate when I can.

**Comment by neilcampbell** [comment]
Thanks @bethesque! Will do.
