### ISSUE TITLE
Upgrade to 1.9.1 standalone

### ISSUE THREAD

**Issue by bethesque** [SEEK-Jobs/pact-net#116]
This version contains some CLI changes, and a bug fix (correcting the usage of Pact::Term headers when replaying the request.)

Changes required to .net code:

- [x] Instead of posting the consumer name, provider name, and pact file write mode in the POST /pact they should now be passed in to the command line `service` call using `--consumer`, `--provider` and `--pact-file-write-mode`. That last POST to /pact does not need a body any more.
- [x] The list of pact URLs passed to the pact verify command should now be space separated arguments rather than a list of comma separated --pact-url options. Eg `pact-provider-verify URL_ONE URL_TWO`

These changes are backwards compatible.

See the full CLI documentation here: https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.9.1

**Comment by neilcampbell** [comment]
Here's a strange one for you.

When the mock provider service runs and there is an old pact file which looks like the file on the left of https://github.com/SEEK-Jobs/pact-net/commit/3e9a1acd534177f1864333814378e1a7a2fcafd8#diff-ff44294f6772432fd207f6542cdb5cf0, then an extra '}' is appended to the bottom of the pact file when overwriting it and the verify fails. https://ci.appveyor.com/project/SEEKJobs/pact-net/build/306

When a pact file exits and looks like the right, everything is generated correctly.

Any idea why the behaviour changes with the different header serialisation variations?

**Comment by bethesque** [comment]
That is the weirdest thing ever. There is a lock taken on the pact file now, so that multiple processes don't corrupt it, but it shouldn't cause that behaviour! Can you try and recreate it with the https://github.com/pact-foundation/pact-ruby-standalone-e2e-example project?

**Comment by neilcampbell** [comment]
@bethesque Yeah strange ay! Yep sure can.

**Comment by neilcampbell** [comment]
cli calls have been updated and a new package released. I am hoping to get some time this weekend to generate a repro of the behaviour I mentioned.

**Comment by neilcampbell** [comment]
@bethesque I managed to create a repro. See https://github.com/neilcampbell/pact-ruby-standalone-e2e-example

I ran:
- ./script/install.sh
- ./script/consumer-create-pact.sh

The pact file ./pacts/foo-bar.json should now have a trailing `}` at the end.

**Comment by bethesque** [comment]
I bumped into it myself today. I've worked out what it is, but I'm unsure if the fix will work on windows, because the documentation for the 'truncate' method said that it wasn't supported on all platforms. I'll release and we'll see!

**Comment by bethesque** [comment]
I've released 1.13.0 of the standalone. Can you give it a go on windows?

**Comment by neilcampbell** [comment]
Yep will do!

**Comment by neilcampbell** [comment]
@bethesque That seems to have fixed it on windows as well. Thanks for sorting that out!
