### ISSUE TITLE
Generate different example values in MinType

### ISSUE THREAD

**Issue by vinogradoff** [SEEK-Jobs/pact-net#117]
Is it possible to generate different values for collections fields?

`MinType( new { id = Match.Type("id")}, 2) `

generates example
```
[
{"id":"id"},
{"id":"id"}
]
```

which fails for some Consumer UnitTest when they are trying to populate a dictionary with the examples.

Ideally I would like to have as example something like
```
[
{"id":"id1"},
{"id":"id2"}
]
```

for this case, autogenerated through pact framework.

**Comment by bethesque** [comment]
It's not currently, but we could add an "each like first” matcher to the
Ruby implementation that would take and return an array, but do the
marching based on the first example.

**Comment by bethesque** [comment]
@uglyog when type=match and min/match=X for an array is specified in the pact, the ruby impl uses the first object in the array as the template, and ignores any others (but prints a warning). What does the jvm impl do when there is an "array like" with more than one example?

**Comment by uglyog** [comment]
The JVM does the same, except for the warning bit

**Comment by bethesque** [comment]
Cool, so it wouldn't break anything. Can you raise a request inhttps://github.com/pact-foundation/pact-support with a reference to this one @vinogradoff
