### ISSUE TITLE
Ruby Regular Expressions Not Fully Supported

### ISSUE THREAD

**Issue by adamrodger** [SEEK-Jobs/pact-net#118]
I was writing a regular expression matcher and wanted a case-insensitive regex to match a GUID. For example, if you wanted to match a hex-style string you might use:
```ruby
/^[0-9A-F]+$/i
```
which would match `ABCD` and `abcd`.

However, this doesn't work because PactNet adds the leading and trailing forward slashes, so you can't specify the case-insensitive flag (or any other modifier after the final forward slash).

**Comment by bethesque** [comment]
As a work around, you could specify 0-9A-Za-z.

**Comment by adamrodger** [comment]
That's exactly what I've done 😀 I was matching a type 4 UUID though so it
makes the regex quite a bit longer. You couldn't use the /x option to
ignore whitespace/comments either.

It does look like you could use the (?i:A-Z) syntax as well, but that's no
more readable

**Comment by neilcampbell** [comment]
@adamrodger Happy to accept a PR on this one 😄
