### ISSUE TITLE
Add xml response body support

### ISSUE THREAD

**Issue by neilcampbell** [SEEK-Jobs/pact-net#17]

**Comment by zezelazo** [comment]
I can help please let me know what are the plans or spec for this, we have our own version of pact-net and we added  some features we can discuss if are aligned to the spec

**Comment by neilcampbell** [comment]
Hi @zezelazo 
Currently we don't really have any plans or spec for supporting XML.
@mefellows @uglyog What are your thoughts on this?

**Comment by uglyog** [comment]
Both the JVM and Rust implementations support XML, so it would be good for the .NET one to support it too.

**Comment by neilcampbell** [comment]
@uglyog Does that include support for v2/3 with matching rules? If so, I'm assuming that is xpath based?

**Comment by mefellows** [comment]
Why was this closed (something I don't know about :) ?)

**Comment by neilcampbell** [comment]
@mefellows Nope, still nothing done on this front. Realistically I don't see this happening any time soon and it's not something I really have a need for. Can re-evaluate later if the ruby core gets support for xml.
