### ISSUE TITLE
Make test output better

### ISSUE THREAD

**Issue by neilcampbell** [SEEK-Jobs/pact-net#3]
The current test output mechanism is fairly primitive and could be a lot better!

I would be nice to use a Reporter abstraction and come up with a nice way of reporting failures. BDDfy may be a good place to start for inspiration.

**Comment by xelibrion** [comment]
We're thinking it would be great to provide a diff similar to what you can get from Fiddler, but in unified format. Another difference would be to display only a request diff on consumer side, and a response diff on provider side. 

![capture](https://cloud.githubusercontent.com/assets/175334/5690331/430399f2-98d6-11e4-8075-0635a28d7d2f.PNG)

We also need to keep in mind that non-exact match is not always invalid as we need to extra items in the consumer request/provider response.

**Comment by neilcampbell** [comment]
Done and release in 1.0.0. I have not implemented any unified unix style diff just yet though. We can decide to do this later.

**Comment by xelibrion** [comment]
@neilcampbell great work with getting the v1 ready!
