### ISSUE TITLE
Ability to set JSON serialization settings

### ISSUE THREAD

**Issue by davidduffett** [SEEK-Jobs/pact-net#38]
I've noticed that the default serialization settings for the request body currently do not serialize null values.

Some rest clients, however, notably RestSharp, do serialize null values and do not directly give you the option to change these settings.  You can get over it by serializing manually using something like JSON.NET in your client.

Could we possibly be able to tweak the serialization settings so that a body can match based on the preferred serialization settings of the app, rather than PACT's preferred settings?  Not sure whether you think this is a good idea....

**Comment by neilcampbell** [comment]
Yeah this is definitely possible, I will come around and have a quick chat to grok the full details.

**Comment by neilcampbell** [comment]
This functionality has been added in 6b07a7c581f17d9395db50e0bf09804cdfc27458, which will be available in the package 1.0.1

**Comment by neilcampbell** [comment]
@screamish Heads up, this is done and will be in the next release.

var pactBuilder = new PactBuilder();
var mockProviderService = pactBuilder.MockService(1234, new JsonSerializerSettings());

**Comment by screamish** [comment]
:+1: 

This will only control the way the body is serialised, yeah? Headers have a separate config?

**Comment by davidduffett** [comment]
:+1: Legend

**Comment by neilcampbell** [comment]
@screamish Headers don't need any serialisation options. They are just sent in the same way you specify them.
