### ISSUE TITLE
Please add feedback on unmatched verify description

### ISSUE THREAD

**Issue by b3hdad** [SEEK-Jobs/pact-net#39]
Thank you for building the pact-net.
Just a small enhancement request.
If the description in the Verify method does not exist in the pact file, currently no feedback is given.
Please enhance so that either it fails the test or prints a warning.
Thank you.

**Comment by neilcampbell** [comment]
Fixed in d4ec496c0ac5f7b1728f77b6a93f5c74c251a524. The verifier will now throw an ArgumentException when no interactions are yielded as a result of the filter being applied.
