### ISSUE TITLE
PACT working with tokens

### ISSUE THREAD

**Issue by abhayachauhan** [SEEK-Jobs/pact-net#40]
Haven't thought a lot about this yet - but has anyone got PACT working with access/identity tokens in headers?

Consumers will have tokens in the request headers, but ensuring they remain valid on the provider side in tests. 

Is there anyway of replacing the token in the pact request on the provider side?

**Comment by neilcampbell** [comment]
I think some of the guys here are doing that, so I will follow up to see what they are doing.

However, if you can deterministically generate the tokens in the consumer, you should also be able to specify them as provider state ("Given" in the consumer dsl), from there the provider can implement the necessary overrides to ensure the token validates or doesn't (depending on your scenario).

**Comment by abhayachauhan** [comment]
It would be great to find out how its working at other places. 

Ideally we wouldn't want to use a token defined at the consumer, as it would require us to inject it into our middleware, and we're going down a path of having a different owin pipeline from production.

We can generate tokens on setup on the provider side, but I suspect the Provider add/override headers in the pact.

@bethesque Any thoughts?

**Comment by bethesque** [comment]
I suspect your solution will be different from the ones I've worked with in Ruby. The verification process in Ruby makes it very easy to mock/stub the authentication code to allow/deny when you want, as the test runs in the same process as the "server" (it's not actually running a server in a separate process, it's just a "request handler" that delegates to the application code).

@uglyog, how have you solved this in the JVM world?

**Comment by bethesque** [comment]
We should write a wiki page on this.

**Comment by abhayachauhan** [comment]
Initially I was thinking of some Provider side token/authorization overriide would be ideal - but reflecting on this, modifying the PACT is far from ideal.
In .NET, our authentication code runs in the same process, so we've done a quick spike and been able to mock our authentication code.

I'm not sure if it would be suitable for PACTNet, but we can open source our middleware, which basically detects mock tokens and hydrates a claims principle.

Thanks @bethesque @neilcampbell

**Comment by neilcampbell** [comment]
@bethesque @abhayachauhan The provider test runs in the same process as well in the Pact-Net, so you can do object level overrides fairly easily. We generally do this on the IoC container and it works pretty well.

**Comment by neilcampbell** [comment]
@abhayachauhan Yeah probably doesn't belong in the Pact project as such, but why not spawn off a small project for the testing middleware.

**Comment by bethesque** [comment]
Sounds like a better solution than messing with getting the tokens "right" in the pact.

**Comment by maxxxxxxxim** [comment]
This is awesome! Helped me straight away... :+1:

**Comment by neilcampbell** [comment]
Awesome stuff @maxxxxxxxim. Glad it helped!

**Comment by lankydeviant** [comment]
> It would be great to find out how its working at other places.
> 
> Ideally we wouldn't want to use a token defined at the consumer, as it would require us to inject it into our middleware, and we're going down a path of having a different owin pipeline from production.
> 
> We can generate tokens on setup on the provider side, but I suspect the Provider would need the ability to add/override the Authorization header in the pact.
> 
> @bethesque Any thoughts?

@abhayachauhan Hi would you be able to show us your implementation of getting the token to work with the custom headers & middleware. We're really struggling to get CustomHeader with Auth to work. Thanks

**Comment by bethesque** [comment]
Here's an example of some Ruby custom middleware that adds an auth header.

```
class AddCustomAuth < Pact::ProviderVerifier::CustomMiddleware
  def initialize app
    @app = app
  end

  def call env
    env['HTTP_AUTHORIZATION'] = 'Basic cGFjdDpwYWN0'
    @app.call(env)
  end
end
```

**Comment by bethesque** [comment]
@lankydeviant what are the problems you're facing with the custom auth header flag?

**Comment by neilcampbell** [comment]
@lankydeviant The samples have an example of some custom auth middleware. See https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs#L105, https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Provider.Api.Web.Tests/TestStartup.cs#L13 and https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Provider.Api.Web.Tests/AuthorizationTokenReplacementMiddleware.cs
