### ISSUE TITLE
Schema instead of Hard Coded Values

### ISSUE THREAD

**Issue by StephenErstad** [SEEK-Jobs/pact-net#49]
Is there a way to test against a particular expected schema instead of hard coded values for the service results in say a Json Schema way?  e.g. This array will exist and not be empty, this string will be n characters long, this property will be null, etc.

**Comment by StephenErstad** [comment]
After looking more closely at the spec, it seems like this is what spec 2-3 are getting closer to this.  The goal is for pact-net to keep up with the spec once out of WIP?

**Comment by neilcampbell** [comment]
Hi @StephenErstad
Thanks for reaching out!

Yes you are correct, that is the goal of the v2 spec which we are working towards slowly. You can track the conversation at https://github.com/SEEK-Jobs/pact-net/issues/9. We are planning to support these specs, it's just a matter of finding the time to do the work.

**Comment by StephenErstad** [comment]
I think I see how I will make it work given the current implementation.

I see huge value in this and will try to get up to speed so I can contribute.

Thanks for the quick response, @neilcampbell.

**Comment by neilcampbell** [comment]
You can do a lot with the current functionality and the use of provider state, so hopefully that should help. However I definitely agree that having more flexibility is going to make things a lot easier!
