### ISSUE TITLE
Unable to use Verify with Basic auth credentials

### ISSUE THREAD

**Issue by sushant2517** [SEEK-Jobs/pact-net#50]
I am trying to point my PactVerifier to a Pact-broker endpoint protected by basic auth. I am able to access the endpoint using any rest client (postman) by passing the credentials in the URL.
http://user:pass@pact-broker/---

But when I use the same URL in the PactUri method and then call Verify, it gives me a 401.

Looks like the HttpClient that is newed up in the PactVerifier doesn't like the credentials passed in the PactUri. Also, since the constructor is internal, there is no way to externally inject the httpclient with configured auth header.

Any ideas/examples of how we can use the pact-broker behind basic auth security?
Any help is highly appreciated. Thanks

**Comment by neilcampbell** [comment]
Thanks for raising this one @sushant2517.
To be honest I have not needed to use the broker with any auth yet, so it's not something explicitly catered for. As you mention it doesn't look like the .NET HttpClient supports user info in the Uri by default, however that is something that can be added fairly easily.

@bethesque How does the Ruby implementation deal with Basic Auth when retrieving a Pact from the broker for the purpose of verification? Do you specify auth details explicitly or use username:password@ in the Uri?

**Comment by sushant2517** [comment]
@neilcampbell Thanks for your reply.
I agree we can add it fairly easily, few approaches I can think of:

1) Overload PactUri method (or optional param) to take in these details via a Request header object
2) Allow a constructor overload to inject a httpclient to be used. That way the consumer code can add the relevant auth-details in the client object and send it over.

I prefer the (2) approach as that would enable using other type of authentication schemes such as tokens etc.
If its ok, I would be happy to add these changes and send you a pull request.

**Comment by neilcampbell** [comment]
@sushant2517 I would like to get Beth's input first, as we are trying to keep the different Pact implementations reasonably consistent.

The other option is to add support in the Uri as you previously mentioned. I have a feeling that is how the Ruby implementation does it.

In regards to option 2, being able to inject a HttpClient wouldn't actually help. You would need to control the HttpRequestMessage object.

**Comment by bethesque** [comment]
Yup, we have basic auth supported for publishing and verifying. 

Verifying: https://github.com/realestate-com-au/pact/wiki/Verifying-pacts#with-basic-auth
Publishing: https://github.com/bethesque/pact_broker-client#consumer

**Comment by bethesque** [comment]
Not sure if seeing the Ruby impl will help or not, but yes, we have a PactURI class that holds the URL and the options: https://github.com/realestate-com-au/pact/blob/110b7e25c00a6a8ac5bdf6876ffab2eaf84158b2/lib/pact/provider/pact_uri.rb

**Comment by sushant2517** [comment]
@bethesque thanks Beth for confirming.
@neilcampbell - I was more referring to remove the creation of the request message object in the Verify method altogether. So basically, we will get an already configured httpclient object from the constructor and we will just make sure that it has the "accept" application/json added to it in the verify method and directly use the Uri configured using the PactUri method.

Another approach would be to passing the request header in the pacturi method and accordingly build the requestmessage object in Verify method.

**Comment by neilcampbell** [comment]
Thanks @bethesque. That is perfect!

@sushant2517 So we should probably do something similar to the Ruby impl and take an optional options param to the PactUri method.

So instead of ```IPactVerifier PactUri(string uri)``` it should be something like ```IPactVerifier PactUri(string uri, PactUriOptions options = null)```.

Did you want to take a crack at implementing this?

**Comment by sushant2517** [comment]
Thanks @neilcampbell and @bethesque.
I will give it a shot sometime today. Thanks guys!

**Comment by neilcampbell** [comment]
@sushant2517 Version 1.0.10 in the Nuget feed includes basic auth. Thanks for the PR.
