### ISSUE TITLE
Using service references

### ISSUE THREAD

**Issue by wxtsxt** [SEEK-Jobs/pact-net#56]
100% if my .net c# integration is done through 'service references' and SOAP messages.
I tried to use pact-net with no success. Is it supported? Will it be? What has to be done? Nothing in readme...

**Comment by neilcampbell** [comment]
Hi @wxtsxt 
Unfortunately Pact does not support xml or SOAP, just JSON HTTP API's.
We are not planning on adding support for this, as we don't have the need.
