### ISSUE TITLE
Partial matching, pact .net

### ISSUE THREAD

**Issue by VanessaDa** [SEEK-Jobs/pact-net#57]
Hi Guys,

I have a JSON pact file with href links that is part of the response body from the consumer. Which looks something like this:

"links": [
              {
                "rel": [
                  "self",
                  "paymentDetail"
                ],
               "href": "/api/uk/account/12345/payment-detail"**
              }
            ]
          },

However the provider  responds with the full resource as below:

"href": "http://localhost:12345/api/uk/customeraccount/123456/payment-detail"

Therefore when I run the provider test and it compares the actual to expected it fails. I am using Pact. Net version 1.1.0 which does not support partial matching as of yet. Is there a work around that anyone knows off that could assist me in which the consumer can ignore the server name?

Regards,
Newbiee

**Comment by neilcampbell** [comment]
Hi @VanessaDa 
This is a tricky situation that I have ran into before, especially if you are testing the traversal of the hypermedia link.

What we ended up doing was standardising on relative uri's for all hypermedia links, so it meant the provider would also return `/api/uk/account/12345/payment-detail` in this case. The host address is then configured as part of creating the http client / consumer.

Hope this helps!
