### ISSUE TITLE
Indirect dependency error message

### ISSUE THREAD

**Issue by ceddlyburge** [SEEK-Jobs/pact-net#59]
HI there
I've recently spent some time grappling with mysterious error messages and persuading a solution to build. I didn't find anything on the internet about it, so I thought I would report it here.
When I first added Pact.Net to my solution everything went very smoothly. I then came back to it a few weeks later, I think having changed absolutely nothing and it wouldn't build. The error messages in visual studio are basically meaningless, but there is something a tiny bit more useful in the build output, as follows:
```The primary reference “blah.dll” could not be resolved because it has an indirect 
dependency on the framework assembly “System.Net.Http, Version=2.2.28.0, 
Culture=neutral, PublicKey Token=b03f5f7f11d50a3a” which could not be resolved 
in the currently targeted framework. “.NETFramework, Version=v4.0”. To resolve 
this problem, either remove the reference “blah.dll” or retarget your application 
to a framework version which contains “System.Net.Http, Version=2.2.28.0, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”```
After a lot of fiddling it turns out that you need to `nuget install-package Microsoft.Net.Http 2.2.28.0` on all projects that reference a project, that contains a reference to pact.net. 
This isn't the latest version of the library, and looking at the Pact.Net source there are no "Use Specific Version" references to this, so it's all a bit confusing. I think it might be because the Microsoft.Bcl package references System.Net.Http, but I didn't get to the bottom of it.
Cheers
Cedd

**Comment by neilcampbell** [comment]
Hmm that is an interesting one. What version of the .NET framework is your project targeting? If it's 4.0 then it requires that additional nuget package (for the HttpClient stuff), however if you are targeting 4.5 or greater you should not need it and can just add a framework reference to System.Net.Http (although that should be added automatically as well when installing PactNet).

**Comment by ceddlyburge** [comment]
HI Neil, just fyi I don't think this is a problem with PactNet, but it might be good to have the solution searchable.

I am targeting .net 4, so it makes sense that I need to add the reference, but having to use that specific version is strange, and having to add the reference to projects that reference a project that references pactnet is also strange. 

I think Microsoft.bcl.build tries to do something clever, which is maybe where the problem is.

**Comment by neilcampbell** [comment]
@ceddlyburge thanks for the reply. Yeah without seeing the full project it's going to be a tricky one to diagnose properly. But yeah .NET 4 isn't out primary use case, so as long as it works and there is a solution searchable, we are all good!
