### ISSUE TITLE
Pacts are not being created 

### ISSUE THREAD

**Issue by AdamDratwa** [SEEK-Jobs/pact-net#75]
Hi. I'm struggling with generating pact file. Either I set PactDir path manually or leave it as default, .json file is not being created. However log file is generated successfully every time. I run test within Resharper and it passes. Any idea what might be wrong?
`PactBuilder = new PactBuilder(new PactConfig {
                PactDir = @"..\..\pacts",
                LogDir = @"..\..\logs"
            });`

**Comment by neilcampbell** [comment]
Hi @AdamDratwa,
Thanks for getting in touch!

The method that actually saves the Pact file is the `Build` method on the `PactBuilder` object.
Just wanted to confirm you are calling it? See https://github.com/SEEK-Jobs/pact-net#2-describe-and-configure-the-pact-as-a-service-consumer-with-a-mock-service

**Comment by AdamDratwa** [comment]
Hi @neilcampbell  Thank you for your response. The issue was caused by not calling Dispose() method after all tests. It's automatically called in your examples which uses xUnit framework, however if you use NUnit you have to invoke it manually like below: ` [OneTimeTearDown]
        public void AfterAll()
        {
            _pact.Dispose();
        }`
Thanks
