### ISSUE TITLE
v2.0 eta

### ISSUE THREAD

**Issue by paulmarshall** [SEEK-Jobs/pact-net#82]
What is the timescale for an implementation of PACT v2 specification in PACT.NET ?

**Comment by neilcampbell** [comment]
Hi @paulmarshall 
There is no timescale for v2 of Pact .NET. You can follow the conversation https://github.com/SEEK-Jobs/pact-net/issues/9 and if you want to contribute, have a look at https://github.com/SEEK-Jobs/pact-net/pull/79
