### ISSUE TITLE
Publishing provider verification results to a Pact Broker

### ISSUE THREAD

**Issue by iamdavidfrancis** [SEEK-Jobs/pact-net#86]
Does PactNet currently support publishing the verification results to a Pact Broker?

**Comment by neilcampbell** [comment]
Not directly from the consumer DSL, however this is something I like to do as a separate activity inside my build pipeline.

Basically:
1. CI runs the build/tests
2. Pact file is exported as a build artefact
3. Chained/dependant build kicks off and consumes the build artefact, analyses any source control or tagging metadata, pushes metadata and Pact file to the Pact broker

Here is a PowerShell script to help with that: https://gist.github.com/neilcampbell/bc1fb7d409425894ece0

**Comment by iamdavidfrancis** [comment]
Thanks, I've been talking with one of the guys on our build team. I think we're going to do something similar as well. Thanks.
