### ISSUE TITLE
Could you add a sample with api controller taking data from other source than memory

### ISSUE THREAD

**Issue by MarcinKowal** [SEEK-Jobs/pact-net#87]
I'm looking an example where pact is being verified against real api controller taking data from source that should be mocked (ie database of remote service) I see that you're using Autofac IoC but wondering how to meet such scenario.

**Comment by neilcampbell** [comment]
Hi @MarcinKowal 
I don't have an example of that exact scenario as the solution is very dependant on your specific scenario, however it is possible.

When creating the PactVerifier and specifying the ServiceProvider, you just supply a new HttpClient with the BaseAddress property set to your running API base url.

Then when defining your custom provider state functions, you would need to either insert directly into the database or call an endpoint on your api that does that for you.

Hopefully that helps!
