### ISSUE TITLE
Incorrect use of HttpClient

### ISSUE THREAD

**Issue by zomgNoUsername** [SEEK-Jobs/pact-net#88]
Hi, did you realize the way you're using HttpClient is not correct?

A client object is mean't to live for the life of the program.
You're not supposed to create a new one, and dispose it each time you use it.

Here is some more info: http://byterot.blogspot.com.au/2016/07/singleton-httpclient-dns.html

May I ask why you're using HttpClient in the first place, when you only have synchronous methods?
I suggest you use WebRequest, or WebClient instead.

If you want to support Async methods as well, by all means use HttpClient; but calling it's methods, and then blocking the thread right away is "odd".

I'll attach some sample code I use as a basis when adding HttpClient to my projects: https://gist.github.com/zomgNoUsername/a99689e78329f79262246b5de56de98d

**Comment by neilcampbell** [comment]
@zomgNoUsername Thanks for getting in touch.
Yes I realise that HttpClient should be shared. Where specifically are you referring to?

**Comment by zomgNoUsername** [comment]
* [The sample code](https://github.com/SEEK-Jobs/pact-net#1-build-your-client)
* [EventsApiClient](https://github.com/SEEK-Jobs/pact-net/blob/master/Samples/EventApi/Consumer/EventsApiClient.cs) _ie not static_
* Test sample code [here](https://github.com/SEEK-Jobs/pact-net/blob/482fc7e1318ce27c6cdbb4710c40e0b0be8ba540/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs#L52) or [here](https://github.com/SEEK-Jobs/pact-net/blob/cadabeb5ba4c93ab239fc74bc44a339dc82ee6d7/PactNet.Tests/IntegrationTests/PactBuilderFailureIntegrationTests.cs#L101)

I understand the consumer of this package could static create an instance of type EventsApiClient, but that public api leaks no details that it uses a new instance of HttpClient internally for each instance you have of EventsApiClient.

It just seems easy to use the api incorrectly (not results -wise, but performance-wise).

**Comment by neilcampbell** [comment]
Yep, so just in the sample usage of Pact. If you look at the Pact library itself it uses a single HttpClient, it's just a slight oversight in the samples.

**Comment by zomgNoUsername** [comment]
OK cool.

I'm not sure what you mean by it's used correctly in the Pact Library, as it's totally up to how the developer chooses to use the type **PactVerifier**. If the example [here](https://github.com/SEEK-Jobs/pact-net#2-tell-the-provider-it-needs-to-honour-the-pact) made it clear that there should only be one instance of the **IPactVerifier** (instead of creating one per test method); I think that would be clear.

**Comment by neilcampbell** [comment]
Pact internally runs a HTTP server, and uses an admin http client to setup interactions etc. That is what I am referring to. Internally there is some HTTP interactions occurring that you are abstracted away from.

In the PactVerifier example, there should only ever be one test to verify a single Pact, so there will never be multiple test methods.

**Comment by zomgNoUsername** [comment]
I see, well I haven't been using the lib yet, this is just me having a quick look though the files.

Thanks Neil.

**Comment by neilcampbell** [comment]
No worries @zomgNoUsername.
I will update the samples a bit to take into account your feedback.
