### ISSUE TITLE
Argument exception when environment variable already exists

### ISSUE THREAD

**Issue by JeanmarcLaiAqovia** [SEEK-Jobs/pact-net#95]
Error occurs when SSL_CERT_FILE environment variable already exists. The error is:

System.ArgumentException : Item has already been added. Key in dictionary: 'ssl_cert_file'  Key being added: 'SSL_CERT_FILE'

I think it is caused by line 41, file PactCoreHost.cs. Would it be possible to update the code so it checks whether the key is already there, as in https://stackoverflow.com/questions/10716800/workaround-to-item-has-already-been-added-key-in-dictionary-using-the-same-ke ?

**Comment by neilcampbell** [comment]
PR merged and is released in 2.0.2-beta
