### ISSUE TITLE
Match regex for Path and Query

### ISSUE THREAD

**Issue by 4l1ce** [SEEK-Jobs/pact-net#98]
Enjoying Pact 2.0 a lot but still have a pain point.
Is that possible to match.Regex for Path and Query?
Can you please share an example if that is possible

Thank you

**Comment by neilcampbell** [comment]
Hi @4l1ce 
Thanks for the feedback!

Only Headers and Body can contain matching rules in the v2 specification.

**Comment by uglyog** [comment]
All attributes of a request should be matchable with v2 specification. Here is the documentation on matching with paths with Pact-JVM: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#matching-on-paths-version-215

**Comment by 4l1ce** [comment]
Thank you for reference!

**Comment by neilcampbell** [comment]
Oh really @uglyog, I had no idea. There are no specification tests for anything other than body and headers, so assumed that was all that was supported.

**Comment by neilcampbell** [comment]
@4l1ce I will look into getting this added soon.

**Comment by neilcampbell** [comment]
This has now been added and is available in the latest beta nuget package 2.0.4-beta
